const DataMenu = [
  {
    id: "1",
    refid: "001",
    headid: "0",
    type: "1",
    caption: "Dashboard",
    target: "/dashboard",
    icon: "dashboard",
  },
  {
    id: "2",
    refid: "001",
    headid: "0",
    type: "1",
    caption: "Booking",
    target: "/booking",
    icon: "event",
  },
  {
    id: "3",
    refid: "002",
    headid: "0",
    type: "2",
    caption: "Code",
    target: "/#",
    icon: "dashboard",
  },
  {
    id: "4",
    refid: "002",
    headid: "0",
    type: "2",
    caption: "Mapping",
    target: "/#",
    icon: "account_tree",
  },
  {
    id: "5",
    refid: "002",
    headid: "0",
    type: "1",
    caption: "XML Link Control",
    target: "/link-control",
    icon: "dataset_linked",
  },
  {
    id: "6",
    refid: "002",
    headid: "0",
    type: "3",
    caption: "",
    icon: "",
  },
  {
    id: "7",
    refid: "002",
    headid: "0",
    type: "1",
    caption: "Company Information",
    icon: "home_work",
  },
  {
    id: "8",
    refid: "002",
    headid: "0",
    type: "3",
    caption: "",
    icon: "",
  },
  {
    id: "9",
    refid: "002",
    headid: "0",
    type: "1",
    caption: "Data Hotel",
    target: "/data-hotel",
    icon: "apartment",
  },
  {
    id: "10",
    refid: "003",
    headid: "0",
    type: "2",
    caption: "Currency",
    icon: "currency_exchange",
  },
  {
    id: "11",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Country Code",
    target: "/code/country-code",
    icon: "dashboard",
  },
  {
    id: "12",
    refid: "",
    headid: "3",
    type: "1",
    caption: "City Code",
    target: "/code/city-code",
    icon: "dashboard",
  },
  {
    id: "31",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Nationality Code",
    target: "/code/nationality-code",
    icon: "dashboard",
  },
  {
    id: "13",
    refid: "",
    headid: "3",
    type: "3",
    caption: "",
    target: "/#",
    icon: "",
  },
  {
    id: "14",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Region",
    target: "/code/region-code",
    icon: "dashboard",
  },
  {
    id: "15",
    refid: "",
    headid: "3",
    type: "1",
    caption: "City Location",
    target: "/code/city-location",
    icon: "dashboard",
  },
  {
    id: "16",
    refid: "",
    headid: "3",
    type: "3",
    caption: "",
    target: "/#",
    icon: "",
  },
  {
    id: "17",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Facilities - Hotel",
    target: "/code/facilities-hotel",
    icon: "dashboard",
  },
  {
    id: "32",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Facilities - Room",
    target: "/code/facilities-room",
    icon: "dashboard",
  },
  {
    id: "18",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Breakfast Code",
    target: "/code/breakfast-code",
    icon: "dashboard",
  },
  {
    id: "19",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Room Grade",
    target: "/code/room-grade",
    icon: "dashboard",
  },
  {
    id: "20",
    refid: "",
    headid: "3",
    type: "3",
    caption: "",
    target: "/#",
    icon: "",
  },
  {
    id: "21",
    refid: "",
    headid: "3",
    type: "1",
    caption: "CXL Policy",
    target: "/code/cxl-policy",
    icon: "dashboard",
  },
  {
    id: "22",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Payment Method",
    target: "/code/payment-method",
    icon: "dashboard",
  },
  {
    id: "23",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Season Type",
    target: "/code/season-type",
    icon: "dashboard",
  },
  {
    id: "24",
    refid: "",
    headid: "3",
    type: "3",
    caption: "",
    target: "/#",
    icon: "",
  },
  {
    id: "25",
    refid: "",
    headid: "3",
    type: "1",
    caption: "Setup Calendar",
    target: "/code/setup-calendar",
    icon: "dashboard",
  },
  {
    id: "26",
    refid: "",
    headid: "4",
    type: "1",
    caption: "Country Mapping",
    target: "/mapping/country",
    icon: "dashboard",
  },
  {
    id: "27",
    refid: "",
    headid: "4",
    type: "1",
    caption: "City Mapping",
    target: "/code/city-mapping",
    icon: "dashboard",
  },
  {
    id: "28",
    refid: "",
    headid: "4",
    type: "1",
    caption: "Hotel Mapping",
    target: "/code/hotel-mapping",
    icon: "dashboard",
  },
  {
    id: "29",
    refid: "",
    headid: "10",
    type: "1",
    caption: "Master Currency",
    target: "/currency/master-currency",
    icon: "dashboard",
  },
  {
    id: "30",
    refid: "",
    headid: "10",
    type: "1",
    caption: "Exchange Rate",
    target: "/currency/exchange-rate",
    icon: "dashboard",
  },
];

export default DataMenu;
