// Redux constant
export const AUTH_PROCESS = "AUTH_PROCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_401 = "AUTH_401";
export const GET_USER_PROCESS = "GET_USER_PROCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const COUNTRY_PROCESS = "COUNTRY_PROCESS";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAILED = "COUNTRY_FAILED";

export const CURRENCIES_SUCCESS = "CURRENCIES_SUCCESS";
export const CURRENCIES_FAILED = "CURRENCIES_FAILED";
export const CURRENCY_PROCESS = "CURRENCY_PROCESS";
export const CURRENCY_SUCCESS = "CURRENCY_SUCCESS";
export const CURRENCY_FAILED = "CURRENCY_FAILED";

export const CITY_PROCESS = "CITY_PROCESS";
export const CITY_SUCCESS = "CITY_SUCCESS";
export const CITY_FAILED = "CITY_FAILED";

export const NATIONALITY_PROCESS = "NATIONALITY_PROCESS";
export const NATIONALITY_SUCCESS = "NATIONALITY_SUCCESS";
export const NATIONALITY_FAILED = "NATIONALITY_FAILED";

export const CITY_LOCATION_PROCESS = "CITY_LOCATION_PROCESS";
export const CITY_LOCATION_SUCCESS = "CITY_LOCATION_SUCCESS";
export const CITY_LOCATION_FAILED = "CITY_LOCATION_FAILED";

export const HOTEL_PROCESS = "HOTEL_PROCESS";
export const HOTEL_SUCCESS = "HOTEL_SUCCESS";
export const HOTEL_FAILED = "HOTEL_FAILED";

export const BOOK_SEARCH_PROCESS = "BOOK_SEARCH_PROCESS";
export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS";
export const BOOK_SEARCH_FAILED = "BOOK_SEARCH_FAILED";
export const BOOK_SEARCH_RESET = "BOOK_SEARCH_RESET";
export const BOOK_LIST_PROCESS = "BOOK_LIST_PROCESS";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAILED = "BOOK_LIST_FAILED";
export const BOOK_DETAIL_PROCESS = "BOOK_DETAIL_PROCESS";
export const BOOK_DETAIL_SUCCESS = "BOOK_DETAIL_SUCCESS";
export const BOOK_DETAIL_FAILED = "BOOK_DETAIL_FAILED";
export const BOOK_SEARCH_ROOM_PROCESS = "BOOK_SEARCH_ROOM_PROCESS";
export const BOOK_SEARCH_ROOM_SUCCESS = "BOOK_SEARCH_ROOM_SUCCESS";
export const BOOK_SEARCH_ROOM_FAILED = "BOOK_SEARCH_ROOM_FAILED";

export const FACILITY_PROCESS = "FACILITY_PROCESS";
export const FACILITY_SUCCESS = "FACILITY_SUCCESS";
export const FACILITY_FAILED = "FACILITY_FAILED";

export const BREAKFAST_PROCESS = "BREAKFAST_PROCESS";
export const BREAKFAST_SUCCESS = "BREAKFAST_SUCCESS";
export const BREAKFAST_FAILED = "BREAKFAST_FAILED";

export const MEAL_PROCESS = "MEAL_PROCESS";
export const MEAL_SUCCESS = "MEAL_SUCCESS";
export const MEAL_FAILED = "MEAL_FAILED";

export const BED_TYPE_PROCESS = "BED_TYPE_PROCESS";
export const BED_TYPE_SUCCESS = "BED_TYPE_SUCCESS";
export const BED_TYPE_FAILED = "BED_TYPE_FAILED";

export const SUPPLIER_PROCESS = "SUPPLIER_PROCESS";
export const SUPPLIER_SUCCESS = "SUPPLIER_SUCCESS";
export const SUPPLIER_FAILED = "SUPPLIER_FAILED";

export const AGENT_PROCESS = "AGENT_PROCESS";
export const AGENT_SUCCESS = "AGENT_SUCCESS";
export const AGENT_FAILED = "AGENT_FAILED";

export const OPERATOR_MANAGEMENT_PROCESS = "OPERATOR_MANAGEMENT_PROCESS";
export const OPERATOR_MANAGEMENT_SUCCESS = "OPERATOR_MANAGEMENT_SUCCESS";
export const OPERATOR_MANAGEMENT_FAILED = "OPERATOR_MANAGEMENT_FAILED";

export const SALES_OFFICE_PROCESS = "SALES_OFFICE_PROCESS";
export const SALES_OFFICE_SUCCESS = "SALES_OFFICE_SUCCESS";
export const SALES_OFFICE_FAILED = "SALES_OFFICE_FAILED";

export const MAPPING_COUNTRY_PROCESS = "MAPPING_COUNTRY_PROCESS";
export const MAPPING_COUNTRY_SUCCESS = "MAPPING_COUNTRY_SUCCESS";
export const MAPPING_COUNTRY_FAILED = "MAPPING_COUNTRY_FAILED";

export const MAPPING_CITY_PROCESS = "MAPPING_CITY_PROCESS";
export const MAPPING_CITY_SUCCESS = "MAPPING_CITY_SUCCESS";
export const MAPPING_CITY_FAILED = "MAPPING_CITY_FAILED";

export const MAPPING_HOTEL_PROCESS = "MAPPING_HOTEL_PROCESS";
export const MAPPING_HOTEL_SUCCESS = "MAPPING_HOTEL_SUCCESS";
export const MAPPING_HOTEL_FAILED = "MAPPING_HOTEL_FAILED";

// Another constant
// export const baseUrl = "https://api-azone.link-webid.com";
// export const baseUrl = "http://localhost:4000";
export const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;