// Redux constant
export const AUTH_PROCESS = "AUTH_PROCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_401 = "AUTH_401";
export const GET_USER_PROCESS = "GET_USER_PROCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const COUNTRY_PROCESS = "COUNTRY_PROCESS";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAILED = "COUNTRY_FAILED";

export const CURRENCIES_SUCCESS = "CURRENCIES_SUCCESS";
export const CURRENCIES_FAILED = "CURRENCIES_FAILED";

export const CITY_PROCESS = "CITY_PROCESS";
export const CITY_SUCCESS = "CITY_SUCCESS";
export const CITY_FAILED = "CITY_FAILED";

export const NATIONALITY_PROCESS = "NATIONALITY_PROCESS";
export const NATIONALITY_SUCCESS = "NATIONALITY_SUCCESS";
export const NATIONALITY_FAILED = "NATIONALITY_FAILED";

export const CITY_LOCATION_PROCESS = "CITY_LOCATION_PROCESS";
export const CITY_LOCATION_SUCCESS = "CITY_LOCATION_SUCCESS";
export const CITY_LOCATION_FAILED = "CITY_LOCATION_FAILED";

export const HOTEL_PROCESS = "HOTEL_PROCESS";
export const HOTEL_SUCCESS = "HOTEL_SUCCESS";
export const HOTEL_FAILED = "HOTEL_FAILED";

export const BOOK_SEARCH_PROCESS = "BOOK_SEARCH_PROCESS";
export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS";
export const BOOK_SEARCH_FAILED = "BOOK_SEARCH_FAILED";
export const BOOK_SEARCH_RESET = "BOOK_SEARCH_RESET";
export const BOOK_LIST_PROCESS = "BOOK_LIST_PROCESS";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAILED = "BOOK_LIST_FAILED";

// Another constant
export const baseUrl = "https://api-azone.link-webid.com";
